/**
 * generate-analytics-scripts.ts — Reads Python source files and generates
 * src/lib/analytics-scripts.ts with all modules embedded as string constants.
 *
 * Run: bun scripts/generate-analytics-scripts.ts
 *
 * This eliminates manual copy-paste between .py files and TS constants.
 * The .py files in scripts/analytics/ are the single source of truth.
 */

import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, relative, basename, dirname } from "node:path";

const ROOT = resolve(import.meta.dirname ?? ".", "..");
const ANALYTICS_DIR = join(ROOT, "scripts", "analytics");
const OUTPUT_FILE = join(ROOT, "src", "lib", "analytics-scripts.ts");

interface PyModule {
  /** Variable name: e.g. PROPHET_FORECAST_PY */
  constName: string;
  /** Sandbox path: e.g. "forecasting/prophet_forecast.py" */
  sandboxPath: string;
  /** Python source code */
  content: string;
  /** Category: charts, forecasting, classification, anomaly */
  category: string;
  /** Human label */
  label: string;
}

function toConstName(relativePath: string): string {
  // e.g. "charts/sales_trends.py" → "SALES_TRENDS_PY"
  // e.g. "main.py" → "MAIN_PY"
  // e.g. "charts/__init__.py" → "CHARTS_INIT_PY"
  return relativePath
    .replace(/\.py$/, "")
    .replace(/\//g, "_")
    .replace(/__/g, "")
    .toUpperCase()
    .replace(/^(\w+)_INIT$/, "$1_INIT")
    + "_PY";
}

function toLabel(filename: string): string {
  return basename(filename, ".py")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function collectPyFiles(dir: string, prefix = ""): PyModule[] {
  const modules: PyModule[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    const relPath = prefix ? `${prefix}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      modules.push(...collectPyFiles(fullPath, relPath));
    } else if (entry.name.endsWith(".py")) {
      const content = readFileSync(fullPath, "utf-8");
      const category = prefix || "root";
      modules.push({
        constName: toConstName(relPath),
        sandboxPath: relPath,
        content,
        category,
        label: toLabel(entry.name),
      });
    }
  }

  return modules;
}

function generateTS(modules: PyModule[]): string {
  const lines: string[] = [];

  lines.push(`/**
 * Analytics Python Scripts — Auto-generated from scripts/analytics/*.py
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Run: bun scripts/generate-analytics-scripts.ts
 *
 * WHY: The analytics engine runs Python inside Agentuity sandboxes.
 * Sandboxes are ephemeral — they start from a snapshot (which has packages
 * like pandas, numpy, matplotlib pre-installed) but have NO application code.
 * All Python files must be uploaded via \`command.files\` on every call.
 *
 * This file embeds the Python source code from \`scripts/analytics/\` as
 * string constants that get bundled into the deployed TypeScript code.
 *
 * SINGLE SOURCE OF TRUTH: The .py files in scripts/analytics/ are canonical.
 * Edit them there, then run the generator to update this file.
 *
 * Generated: ${new Date().toISOString()}
 * Modules: ${modules.length}
 */
`);

  // Group by category
  const categories = new Map<string, PyModule[]>();
  for (const mod of modules) {
    const cat = mod.category;
    if (!categories.has(cat)) categories.set(cat, []);
    categories.get(cat)!.push(mod);
  }

  // Category display order
  const categoryOrder = ["root", "charts", "forecasting", "classification", "anomaly"];
  const categoryLabels: Record<string, string> = {
    root: "Entry Point & Utilities",
    charts: "Chart Modules",
    forecasting: "Forecasting Modules",
    classification: "Classification Modules",
    anomaly: "Anomaly Detection Modules",
  };

  for (const cat of categoryOrder) {
    const mods = categories.get(cat);
    if (!mods || mods.length === 0) continue;

    const label = categoryLabels[cat] || cat;
    lines.push(`// ${"─".repeat(60)}`);
    lines.push(`// ${label}`);
    lines.push(`// ${"─".repeat(60)}`);
    lines.push("");

    for (const mod of mods) {
      // Escape backticks and ${} in the Python source
      const escaped = mod.content
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$\{/g, "\\${");

      lines.push(`export const ${mod.constName} = \`${escaped}\`;`);
      lines.push("");
    }
  }

  // File manifest
  lines.push(`// ${"─".repeat(60)}`);
  lines.push(`// File manifest — uploaded to sandbox via command.files`);
  lines.push(`// ${"─".repeat(60)}`);
  lines.push("");
  lines.push(`/**
 * All Python files needed in the sandbox, in the format expected by
 * sandboxApi.run({ command: { files: [...] } }).
 *
 * The data payload (input.json) is NOT included here — it's added
 * dynamically by the analytics runner.
 */
export interface SandboxFile {
  path: string;
  content: string;
}

export function getAnalyticsFiles(): SandboxFile[] {
  return [`);

  for (const mod of modules) {
    lines.push(`    { path: "${mod.sandboxPath}", content: ${mod.constName} },`);
  }

  lines.push(`  ];`);
  lines.push(`}`);
  lines.push("");

  return lines.join("\n");
}

// ── Main ──

const modules = collectPyFiles(ANALYTICS_DIR);
const output = generateTS(modules);
writeFileSync(OUTPUT_FILE, output, "utf-8");

console.log(`✓ Generated ${OUTPUT_FILE}`);
console.log(`  ${modules.length} Python modules embedded:`);

const byCategory = new Map<string, number>();
for (const m of modules) {
  byCategory.set(m.category, (byCategory.get(m.category) || 0) + 1);
}
for (const [cat, count] of byCategory) {
  console.log(`    ${cat}: ${count} files`);
}
